{{- if .Values.server.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server.fullname" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      {{- include "server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.server.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      containers:
        - name: server
          command:
            - sh
            - -c 
            - >
              {{- if .Values.server.envFiles }}
              export $(xargs < {{ join " " .Values.server.envFiles }});
              {{- end }}
              sh /root/configs/docker/cmd.sh
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          {{- if or .Values.server.env .Values.server.extraSecretEnvironmentVars .Values.databaseSecret.enabled }}
          env:
              - name: PSONO_URL_PREFIX
                value: "server/"
            {{- range $key, $val := .Values.server.env }}
              - name: {{ $key | quote }}
                value: {{ $val | quote }}
            {{- end }}
            {{ if .Values.databaseSecret.enabled }}
              - name: PSONO_DATABASES_DEFAULT_USER
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.databaseSecret.name }}
                    key: {{ .Values.databaseSecret.usernameKey }}
              - name: PSONO_DATABASES_DEFAULT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.databaseSecret.name }}
                    key: {{ .Values.databaseSecret.passwordKey }}
            {{ end }}
            {{- range .Values.server.extraSecretEnvironmentVars }}
              - name: {{ .envName }}
                valueFrom:
                  secretKeyRef:
                    name: {{ .secretName }}
                    key: {{ .secretKey }}
            {{- end }}
          {{- end }}
          {{- if .Values.secrets.create }}
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.name }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/www/html
            {{- if .Values.server.extraVolumeMounts }}
              {{ toYaml .Values.server.extraVolumeMounts | nindent 12 }}
            {{- end }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          emptyDir: {}
      {{- if .Values.server.extraVolumes }}
        {{ toYaml .Values.server.extraVolumes | nindent 8}}
      {{- end }}
{{- end }}